In [1]:
%pip install pandas scikit-learn matplotlib nltk

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.1.0)
Requirement already satisfied: scikit-learn in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.1)
Requirement already satisfied: matplotlib in .\AppData\Roaming\Python\Python313\site-packages (3.11.0)
Requirement already satisfied: nltk in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.10.4)
Requirement already satisfied: numpy>=2.0.2 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.9.0 in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: contourpy>=1.0.1 in .\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in .\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: defusedxml in .\AppData\Roaming\Python\Python313\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: regex>=2021.8.3 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (2026.9.29)
Requirement already satisfied: tqdm in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (4.70.1)
Requirement already satisfied: cloudpickle>=3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python313\site-packages (from tqdm->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from pathlib import Path

PROJECT_DIR = Path.cwd()
DOCS_DIR = PROJECT_DIR / "documents"
OUTPUT_DIR = PROJECT_DIR / "outputs"

DOCS_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)

documents = {
    "python.txt": """
Python is a high-level programming language.
Python is used in automation, web development,
data analysis, artificial intelligence and machine learning.
Pandas is a Python library used for data manipulation.
Scikit-learn provides tools for machine learning.
""",

    "machine_learning.txt": """
Machine learning is a branch of artificial intelligence.
It enables computers to learn patterns from data.
Supervised learning uses labelled training examples.
Classification predicts categories.
Regression predicts numerical values.
""",

    "college.txt": """
Students should carry their college identification cards.
Students should follow college attendance rules.
Laboratory sessions provide practical learning experience.
Students should submit assignments before deadlines.
""",

    "project.txt": """
A document question-answering assistant answers questions
using information from a collection of documents.
The system splits documents into smaller text chunks.
TF-IDF represents text using term importance.
Cosine similarity compares questions with document passages.
The assistant displays supporting passages and source filenames.
If information is unavailable, it reports that it was not found.
"""
}

for filename, content in documents.items():
    (DOCS_DIR / filename).write_text(
        content.strip(),
        encoding="utf-8"
    )

print("Sample documents created successfully!")

for file in sorted(DOCS_DIR.glob("*.txt")):
    print(file.name)

Sample documents created successfully!
college.txt
machine_learning.txt
project.txt
python.txt

In [3]:
corpus = {}

for file in sorted(DOCS_DIR.glob("*.txt")):
    text = file.read_text(encoding="utf-8").strip()

    if text:
        corpus[file.name] = text

print("Total documents:", len(corpus))

for filename, text in corpus.items():
    print(filename, "-", len(text.split()), "words")

Total documents: 4
college.txt - 25 words
machine_learning.txt - 29 words
project.txt - 53 words
python.txt - 35 words

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2)
)

chunk_texts = [chunk["text"] for chunk in chunks]

tfidf_matrix = vectorizer.fit_transform(chunk_texts)

print("TF-IDF matrix shape:", tfidf_matrix.shape)
print("Document retrieval system is ready!")

TF-IDF matrix shape: (4, 183)
Document retrieval system is ready!

In [13]:
import re
import pandas as pd

def create_chunks(text, max_words=80, overlap_sentences=1):
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    chunks = []
    current = []

    for sentence in sentences:
        if not sentence.strip():
            continue

        if current and len((" ".join(current + [sentence])).split()) > max_words:
            chunks.append(" ".join(current))
            current = current[-overlap_sentences:] if overlap_sentences else []

        current.append(sentence)

    if current:
        chunks.append(" ".join(current))

    return chunks


chunks = []

for filename, text in corpus.items():
    for i, chunk_text in enumerate(create_chunks(text)):
        chunks.append({
            "source": filename,
            "chunk_id": i + 1,
            "text": chunk_text
        })

chunks_df = pd.DataFrame(chunks)

print("Total text chunks:", len(chunks_df))
display(chunks_df)

Total text chunks: 4

,source,chunk_id,text
0,college.txt,1,Students should carry their college identifica...
1,machine_learning.txt,1,Machine learning is a branch of artificial int...
2,project.txt,1,A document question-answering assistant answer...
3,python.txt,1,Python is a high-level programming language. P...

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

chunk_texts = [chunk["text"] for chunk in chunks]

vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    ngram_range=(1, 2)
)

tfidf_matrix = vectorizer.fit_transform(chunk_texts)

print("Chunks:", len(chunks))
print("Vocabulary size:", len(vectorizer.vocabulary_))
print("TF-IDF system rebuilt!")

Chunks: 4
Vocabulary size: 183
TF-IDF system rebuilt!

In [6]:
import re

MIN_SIMILARITY = 0.12

def answer_question(question, top_k=3):
    question = question.strip()

    if not question:
        return {"answer": "Please enter a question."}

    query_vector = vectorizer.transform([question])

    scores = cosine_similarity(
        query_vector, tfidf_matrix
    ).flatten()

    ranked_indices = scores.argsort()[::-1][:top_k]
    best_idx = int(ranked_indices[0])
    best_score = float(scores[best_idx])

    retrieved = []

    for idx in ranked_indices:
        retrieved.append({
            "source": chunks[idx]["source"],
            "chunk_id": chunks[idx]["chunk_id"],
            "passage": chunks[idx]["text"],
            "score": round(float(scores[idx]), 3)
        })

    if best_score < MIN_SIMILARITY:
        return {
            "answer": "Information not found in provided document.",
            "source": None,
            "passage": None,
            "score": best_score,
            "retrieved": pd.DataFrame(retrieved)
        }

    best_chunk = chunks[best_idx]

    sentences = re.split(
        r"(?<=[.!?])\s+",
        best_chunk["text"]
    )

    sentence_vectors = vectorizer.transform(sentences)

    sentence_scores = cosine_similarity(
        query_vector, sentence_vectors
    ).flatten()

    best_sentence_idx = int(sentence_scores.argmax())

    return {
        "answer": sentences[best_sentence_idx],
        "source": best_chunk["source"],
        "passage": best_chunk["text"],
        "score": best_score,
        "retrieved": pd.DataFrame(retrieved)
    }


def display_answer(question):
    result = answer_question(question)

    print("Question:", question)
    print("\nAnswer:", result["answer"])
    print("Similarity score:", round(result.get("score", 0), 3))

    if result.get("source"):
        print("\nSource document:", result["source"])
        print("Supporting passage:", result["passage"])
    else:
        print("\nNo sufficiently relevant source passage found.")

    if "retrieved" in result:
        print("\nTop retrieved passages:")
        display(result["retrieved"])

    return result

In [7]:
display_answer("What is machine learning?")

Question: What is machine learning?

Answer: Scikit-learn provides tools for machine learning.
Similarity score: 0.325

Source document: python.txt
Supporting passage: Python is a high-level programming language. Python is used in automation, web development, data analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.

Top retrieved passages:

,source,chunk_id,passage,score
0,python.txt,1,Python is a high-level programming language. P...,0.325
1,machine_learning.txt,1,Machine learning is a branch of artificial int...,0.242
2,college.txt,1,Students should carry their college identifica...,0.047

{'answer': 'Scikit-learn provides tools for machine learning.',
 'source': 'python.txt',
 'passage': 'Python is a high-level programming language. Python is used in automation, web development, data analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.',
 'score': 0.324825032002327,
 'retrieved':                  source  chunk_id  \
 0            python.txt         1
 1  machine_learning.txt         1
 2           college.txt         1

                                              passage  score
 0  Python is a high-level programming language. P...  0.325
 1  Machine learning is a branch of artificial int...  0.242
 2  Students should carry their college identifica...  0.047  }

In [8]:
display_answer(
    "Which Python library is used for data manipulation?"
)

Question: Which Python library is used for data manipulation?

Answer: Pandas is a Python library used for data manipulation.
Similarity score: 0.527

Source document: python.txt
Supporting passage: Python is a high-level programming language. Python is used in automation, web development, data analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.

Top retrieved passages:

,source,chunk_id,passage,score
0,python.txt,1,Python is a high-level programming language. P...,0.527
1,machine_learning.txt,1,Machine learning is a branch of artificial int...,0.032
2,project.txt,1,A document question-answering assistant answer...,0.000

{'answer': 'Pandas is a Python library used for data manipulation.',
 'source': 'python.txt',
 'passage': 'Python is a high-level programming language. Python is used in automation, web development, data analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.',
 'score': 0.5271082501881932,
 'retrieved':                  source  chunk_id  \
 0            python.txt         1
 1  machine_learning.txt         1
 2           project.txt         1

                                              passage  score
 0  Python is a high-level programming language. P...  0.527
 1  Machine learning is a branch of artificial int...  0.032
 2  A document question-answering assistant answer...  0.000  }

In [9]:
display_answer(
    "Who won the FIFA World Cup in 2034?"
)

Question: Who won the FIFA World Cup in 2034?

Answer: Information not found in provided document.
Similarity score: 0.0

No sufficiently relevant source passage found.

Top retrieved passages:

,source,chunk_id,passage,score
0,python.txt,1,Python is a high-level programming language. P...,0.0
1,project.txt,1,A document question-answering assistant answer...,0.0
2,machine_learning.txt,1,Machine learning is a branch of artificial int...,0.0

{'answer': 'Information not found in provided document.',
 'source': None,
 'passage': None,
 'score': 0.0,
 'retrieved':                  source  chunk_id  \
 0            python.txt         1
 1           project.txt         1
 2  machine_learning.txt         1

                                              passage  score
 0  Python is a high-level programming language. P...    0.0
 1  A document question-answering assistant answer...    0.0
 2  Machine learning is a branch of artificial int...    0.0  }

In [10]:
test_questions = [
    "What is Python used for?",
    "What is supervised learning?",
    "Which library is used for data manipulation?",
    "What does cosine similarity compare?",
    "What are the college attendance rules?",
    "Who won the FIFA World Cup in 2034?"
]

test_results = []

for question in test_questions:
    result = answer_question(question)

    test_results.append({
        "Question": question,
        "Answer": result["answer"],
        "Source": result.get("source") or "Not found",
        "Similarity": round(result.get("score", 0), 3)
    })

test_df = pd.DataFrame(test_results)

display(test_df)

,Question,Answer,Source,Similarity
0,What is Python used for?,"Python is used in automation, web development,...",python.txt,0.438
1,What is supervised learning?,Supervised learning uses labelled training exa...,machine_learning.txt,0.274
2,Which library is used for data manipulation?,Pandas is a Python library used for data manip...,python.txt,0.405
3,What does cosine similarity compare?,Cosine similarity compares questions with docu...,project.txt,0.184
4,What are the college attendance rules?,Students should follow college attendance rules.,college.txt,0.394
5,Who won the FIFA World Cup in 2034?,Information not found in provided document.,Not found,0.000

In [11]:
test_df.to_csv(
    OUTPUT_DIR / "test_results.csv",
    index=False
)

with open(
    OUTPUT_DIR / "sample_transcripts.txt",
    "w",
    encoding="utf-8"
) as file:
    for question in test_questions:
        result = answer_question(question)

        file.write(f"Question: {question}\n")
        file.write(f"Answer: {result['answer']}\n")
        file.write(
            f"Source: {result.get('source') or 'Not found'}\n"
        )

        if result.get("passage"):
            file.write(
                f"Supporting passage: {result['passage']}\n"
            )

        file.write("\n" + "-" * 50 + "\n\n")

print("Test results and transcripts saved successfully!")

Test results and transcripts saved successfully!

In [12]:
print("Project folder:", PROJECT_DIR)
print("\nSaved output files:")

for file in sorted(OUTPUT_DIR.iterdir()):
    print(file.name)

Project folder: C:\Users\maham

Saved output files:
sample_transcripts.txt
test_results.csv

In [19]:
question = "What is machine learning?"

query_vector = vectorizer.transform([question])

scores = cosine_similarity(
    query_vector, tfidf_matrix
).flatten()

print("Question:", question)
print("Scores:", scores)
print("Best score:", scores.max())

Question: What is machine learning?
Scores: [0.04654982 0.24154318 0.         0.32482503]
Best score: 0.324825032002327

In [20]:
display_answer("What is machine learning?")

Question: What is machine learning?

Answer: Scikit-learn provides tools for machine learning.
Similarity score: 0.325

Source document: python.txt
Supporting passage: Python is a high-level programming language. Python is used in automation, web development,
data analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.

Top retrieved passages:

,source,chunk_id,passage,score
0,python.txt,1,Python is a high-level programming language. P...,0.325
1,machine_learning.txt,1,Machine learning is a branch of artificial int...,0.242
2,college.txt,1,Students should carry their college identifica...,0.047

{'answer': 'Scikit-learn provides tools for machine learning.',
 'source': 'python.txt',
 'passage': 'Python is a high-level programming language. Python is used in automation, web development,\ndata analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.',
 'score': 0.324825032002327,
 'retrieved':                  source  chunk_id  \
 0            python.txt         1
 1  machine_learning.txt         1
 2           college.txt         1

                                              passage  score
 0  Python is a high-level programming language. P...  0.325
 1  Machine learning is a branch of artificial int...  0.242
 2  Students should carry their college identifica...  0.047  }

In [21]:
def answer_question(question, top_k=3):
    question = question.strip()

    if not question:
        return {"answer": "Please enter a question."}

    query_vector = vectorizer.transform([question])
    chunk_texts = [chunk["text"] for chunk in chunks]

    chunk_scores = cosine_similarity(
        query_vector, tfidf_matrix
    ).flatten()

    ranked_indices = chunk_scores.argsort()[::-1][:top_k]

    retrieved = []
    for idx in ranked_indices:
        retrieved.append({
            "source": chunks[idx]["source"],
            "chunk_id": chunks[idx]["chunk_id"],
            "passage": chunks[idx]["text"],
            "score": round(float(chunk_scores[idx]), 3)
        })

    # Find the best matching sentence across all chunks
    candidates = []

    for idx, chunk in enumerate(chunks):
        sentences = re.split(
            r'(?<=[.!?])\s+', chunk["text"]
        )

        for sentence in sentences:
            if not sentence.strip():
                continue

            sentence_vector = vectorizer.transform([sentence])
            score = cosine_similarity(
                query_vector, sentence_vector
            )[0][0]

            candidates.append({
                "sentence": sentence,
                "source": chunk["source"],
                "passage": chunk["text"],
                "score": float(score)
            })

    best = max(candidates, key=lambda x: x["score"])

    if best["score"] < 0.12:
        return {
            "answer": "Information not found in provided document.",
            "source": None,
            "passage": None,
            "score": best["score"],
            "retrieved": pd.DataFrame(retrieved)
        }

    return {
        "answer": best["sentence"],
        "source": best["source"],
        "passage": best["passage"],
        "score": best["score"],
        "retrieved": pd.DataFrame(retrieved)
    }


print("Improved answer selection is ready!")

Improved answer selection is ready!

In [22]:
display_answer("What is machine learning?")

Question: What is machine learning?

Answer: Machine learning is a branch of artificial intelligence.
Similarity score: 0.503

Source document: machine_learning.txt
Supporting passage: Machine learning is a branch of artificial intelligence. It enables computers to learn patterns from data. Supervised learning uses labelled training examples. Classification predicts categories. Regression predicts numerical values.

Top retrieved passages:

,source,chunk_id,passage,score
0,python.txt,1,Python is a high-level programming language. P...,0.325
1,machine_learning.txt,1,Machine learning is a branch of artificial int...,0.242
2,college.txt,1,Students should carry their college identifica...,0.047

{'answer': 'Machine learning is a branch of artificial intelligence.',
 'source': 'machine_learning.txt',
 'passage': 'Machine learning is a branch of artificial intelligence. It enables computers to learn patterns from data. Supervised learning uses labelled training examples. Classification predicts categories. Regression predicts numerical values.',
 'score': 0.5033275339842773,
 'retrieved':                  source  chunk_id  \
 0            python.txt         1
 1  machine_learning.txt         1
 2           college.txt         1

                                              passage  score
 0  Python is a high-level programming language. P...  0.325
 1  Machine learning is a branch of artificial int...  0.242
 2  Students should carry their college identifica...  0.047  }

In [23]:
display_answer("Which library is used for data manipulation?")

Question: Which library is used for data manipulation?

Answer: Pandas is a Python library used for data manipulation.
Similarity score: 0.79

Source document: python.txt
Supporting passage: Python is a high-level programming language. Python is used in automation, web development,
data analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.

Top retrieved passages:

,source,chunk_id,passage,score
0,python.txt,1,Python is a high-level programming language. P...,0.405
1,machine_learning.txt,1,Machine learning is a branch of artificial int...,0.036
2,project.txt,1,A document question-answering assistant answer...,0.000

{'answer': 'Pandas is a Python library used for data manipulation.',
 'source': 'python.txt',
 'passage': 'Python is a high-level programming language. Python is used in automation, web development,\ndata analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.',
 'score': 0.7895623108901775,
 'retrieved':                  source  chunk_id  \
 0            python.txt         1
 1  machine_learning.txt         1
 2           project.txt         1

                                              passage  score
 0  Python is a high-level programming language. P...  0.405
 1  Machine learning is a branch of artificial int...  0.036
 2  A document question-answering assistant answer...  0.000  }

In [24]:
display_answer("Who won the FIFA World Cup in 2034?")

Question: Who won the FIFA World Cup in 2034?

Answer: Information not found in provided document.
Similarity score: 0.0

No sufficiently relevant source passage found.

Top retrieved passages:

,source,chunk_id,passage,score
0,python.txt,1,Python is a high-level programming language. P...,0.0
1,project.txt,1,A document question-answering assistant answer...,0.0
2,machine_learning.txt,1,Machine learning is a branch of artificial int...,0.0

{'answer': 'Information not found in provided document.',
 'source': None,
 'passage': None,
 'score': 0.0,
 'retrieved':                  source  chunk_id  \
 0            python.txt         1
 1           project.txt         1
 2  machine_learning.txt         1

                                              passage  score
 0  Python is a high-level programming language. P...    0.0
 1  A document question-answering assistant answer...    0.0
 2  Machine learning is a branch of artificial int...    0.0  }

In [25]:
display_answer(
    "Which library is used for data manipulation?"
)

Question: Which library is used for data manipulation?

Answer: Pandas is a Python library used for data manipulation.
Similarity score: 0.79

Source document: python.txt
Supporting passage: Python is a high-level programming language. Python is used in automation, web development,
data analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.

Top retrieved passages:

,source,chunk_id,passage,score
0,python.txt,1,Python is a high-level programming language. P...,0.405
1,machine_learning.txt,1,Machine learning is a branch of artificial int...,0.036
2,project.txt,1,A document question-answering assistant answer...,0.000

{'answer': 'Pandas is a Python library used for data manipulation.',
 'source': 'python.txt',
 'passage': 'Python is a high-level programming language. Python is used in automation, web development,\ndata analysis, artificial intelligence and machine learning. Pandas is a Python library used for data manipulation. Scikit-learn provides tools for machine learning.',
 'score': 0.7895623108901775,
 'retrieved':                  source  chunk_id  \
 0            python.txt         1
 1  machine_learning.txt         1
 2           project.txt         1

                                              passage  score
 0  Python is a high-level programming language. P...  0.405
 1  Machine learning is a branch of artificial int...  0.036
 2  A document question-answering assistant answer...  0.000  }

In [26]:
test_questions = [
    "What is Python used for?",
    "What is machine learning?",
    "Which library is used for data manipulation?",
    "What does cosine similarity compare?",
    "What are the college attendance rules?",
    "Who won the FIFA World Cup in 2034?",
    "What is the capital of Japan?",
    "What is quantum computing?"
]

test_results = []

for question in test_questions:
    result = answer_question(question)

    test_results.append({
        "Question": question,
        "Answer": result["answer"],
        "Source": result.get("source") or "Not found",
        "Similarity Score": round(result.get("score", 0), 3)
    })

test_df = pd.DataFrame(test_results)
display(test_df)

,Question,Answer,Source,Similarity Score
0,What is Python used for?,"Python is used in automation, web development,...",python.txt,0.407
1,What is machine learning?,Machine learning is a branch of artificial int...,machine_learning.txt,0.503
2,Which library is used for data manipulation?,Pandas is a Python library used for data manip...,python.txt,0.790
3,What does cosine similarity compare?,Cosine similarity compares questions with docu...,project.txt,0.522
4,What are the college attendance rules?,Students should follow college attendance rules.,college.txt,0.745
5,Who won the FIFA World Cup in 2034?,Information not found in provided document.,Not found,0.000
6,What is the capital of Japan?,Information not found in provided document.,Not found,0.000
7,What is quantum computing?,Information not found in provided document.,Not found,0.000

In [29]:
%pip install gradio pypdf

Collecting gradio
  Downloading gradio-6.30.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: pypdf in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (6.21.2)
Requirement already satisfied: anyio<5.0,>=3.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (4.14.1)
Collecting audioop-lts<=0.2.2 (from gradio)
  Downloading audioop_lts-0.2.2-cp313-abi3-win_amd64.whl.metadata (2.0 kB)
Collecting brotli>=1.1.0 (from gradio)
  Downloading brotli-1.2.1-cp313-cp313-win_amd64.whl.metadata (6.3 kB)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.161.1-py3-none-any.whl.metadata (26 kB)
Collecting gradio-client==2.7.2 (from gradio)
  Downloading gradio_client-2.7.2-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio)
  Downloading groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Collecting hf-gradio<1.0,>=0.4.1 (from gradio)
  Downloading hf_gradio-0.4.1-py3-none-any.whl.metadata (428 bytes)
Requirement already satisfied: httpx<1.0,>=0.24.1 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (0.28.1)
Collecting huggingface-hub<3.0,>=1.16.0 (from gradio)
  Downloading huggingface_hub-2.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: jinja2<4.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (2.5.0)
Collecting orjson~=3.0 (from gradio)
  Downloading orjson-3.13.0-cp313-cp313-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: packaging in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (26.2)
Requirement already satisfied: pandas<4.0,>=1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (3.1.0)
Requirement already satisfied: pillow<13.0,>=8.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (12.3.0)
Collecting pydantic<=3.0,>=2.0 (from gradio)
  Downloading pydantic-2.14.1-py3-none-any.whl.metadata (133 kB)
Collecting pydub<1.0 (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart<1.0,>=0.0.18 (from gradio)
  Downloading python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Collecting pytz>=2017.2 (from gradio)
  Downloading pytz-2026.5-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (6.0.3)
Collecting safehttpx<0.2.0,>=0.1.7 (from gradio)
  Downloading safehttpx-0.1.7-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<2.0,>=1.0.1 (from gradio)
  Downloading starlette-1.9.0-py3-none-any.whl.metadata (6.6 kB)
Collecting tomlkit<0.15.0,>=0.12.0 (from gradio)
  Downloading tomlkit-0.14.0-py3-none-any.whl.metadata (2.8 kB)
Collecting typer<1.0,>=0.12 (from gradio)
  Using cached typer-0.27.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: typing-extensions~=4.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (4.16.0)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.54.0-py3-none-any.whl.metadata (6.6 kB)
Collecting fsspec (from gradio-client==2.7.2->gradio)
  Using cached fsspec-2026.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna>=2.8 in .\AppData\Roaming\Python\Python313\site-packages (from anyio<5.0,>=3.0->gradio) (3.18)
Collecting typing-inspection>=0.4.2 (from fastapi<1.0,>=0.115.2->gradio)
  Downloading typing_inspection-0.4.4-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi<1.0,>=0.115.2->gradio)
  Using cached annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Collecting opentelemetry-api>=1.44.0 (from fastapi<1.0,>=0.115.2->gradio)
  Downloading opentelemetry_api-1.45.1-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: certifi in .\AppData\Roaming\Python\Python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (2026.6.17)
Requirement already satisfied: httpcore==1.* in .\AppData\Roaming\Python\Python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in .\AppData\Roaming\Python\Python313\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (8.5.0)
Collecting filelock>=3.10.0 (from huggingface-hub<3.0,>=1.16.0->gradio)
  Downloading filelock-4.2.4-py3-none-any.whl.metadata (2.0 kB)
Collecting hf-xet<2.0.0,>=1.6.0 (from huggingface-hub<3.0,>=1.16.0->gradio)
  Using cached hf_xet-1.7.0-cp38-abi3-win_amd64.whl.metadata (4.9 kB)
Collecting httpx2<3,>=2.0.0 (from huggingface-hub<3.0,>=1.16.0->gradio)
  Downloading httpx2-2.16.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: tqdm>=4.42.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (4.70.1)
Collecting httpcore2==2.16.0 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.16.0->gradio)
  Downloading httpcore2-2.16.0-py3-none-any.whl.metadata (27 kB)
Collecting truststore>=0.10 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.16.0->gradio)
  Downloading truststore-0.10.5-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: python-dateutil>=2.9.0 in .\AppData\Roaming\Python\Python313\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python313\site-packages (from pandas<4.0,>=1.0->gradio) (2026.2)
Collecting annotated-types>=0.6.0 (from pydantic<=3.0,>=2.0->gradio)
  Downloading annotated_types-0.8.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.50.1 (from pydantic<=3.0,>=2.0->gradio)
  Downloading pydantic_core-2.50.1-cp313-cp313-win_amd64.whl.metadata (6.7 kB)
Collecting shellingham>=1.3.0 (from typer<1.0,>=0.12->gradio)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer<1.0,>=0.12->gradio)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python313\site-packages (from typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.9.0->pandas<4.0,>=1.0->gradio) (1.17.0)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer<1.0,>=0.12->gradio)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Roaming\Python\Python313\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading gradio-6.30.0-py3-none-any.whl (31.4 MB)
   ---------------------------------------- 0.0/31.4 MB ? eta -:--:--
   - -------------------------------------- 1.3/31.4 MB 7.0 MB/s eta 0:00:05
   -- ------------------------------------- 2.1/31.4 MB 6.2 MB/s eta 0:00:05
   ---- ----------------------------------- 3.1/31.4 MB 5.2 MB/s eta 0:00:06
   ----- ---------------------------------- 4.2/31.4 MB 5.1 MB/s eta 0:00:06
   ------- -------------------------------- 5.5/31.4 MB 5.5 MB/s eta 0:00:05
   --------- ------------------------------ 7.1/31.4 MB 5.8 MB/s eta 0:00:05
   ----------- ---------------------------- 8.7/31.4 MB 5.9 MB/s eta 0:00:04
   ------------ --------------------------- 10.0/31.4 MB 6.1 MB/s eta 0:00:04
   -------------- ------------------------- 11.5/31.4 MB 6.2 MB/s eta 0:00:04
   ---------------- ----------------------- 12.8/31.4 MB 6.3 MB/s eta 0:00:03
   ------------------ --------------------- 14.4/31.4 MB 6.3 MB/s eta 0:00:03
   -------------------- ------------------- 16.0/31.4 MB 6.4 MB/s eta 0:00:03
   ---------------------- ----------------- 17.6/31.4 MB 6.5 MB/s eta 0:00:03
   ------------------------ --------------- 19.1/31.4 MB 6.5 MB/s eta 0:00:02
   -------------------------- ------------- 20.4/31.4 MB 6.5 MB/s eta 0:00:02
   --------------------------- ------------ 21.8/31.4 MB 6.6 MB/s eta 0:00:02
   ----------------------------- ---------- 23.3/31.4 MB 6.6 MB/s eta 0:00:02
   ------------------------------- -------- 24.9/31.4 MB 6.6 MB/s eta 0:00:01
   --------------------------------- ------ 26.2/31.4 MB 6.6 MB/s eta 0:00:01
   ----------------------------------- ---- 27.8/31.4 MB 6.7 MB/s eta 0:00:01
   ------------------------------------- -- 29.4/31.4 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------  30.7/31.4 MB 6.7 MB/s eta 0:00:01
   ---------------------------------------- 31.4/31.4 MB 6.6 MB/s  0:00:04
Downloading gradio_client-2.7.2-py3-none-any.whl (64 kB)
Downloading audioop_lts-0.2.2-cp313-abi3-win_amd64.whl (30 kB)
Downloading fastapi-0.161.1-py3-none-any.whl (149 kB)
Downloading groovy-0.1.2-py3-none-any.whl (14 kB)
Downloading hf_gradio-0.4.1-py3-none-any.whl (4.5 kB)
Downloading huggingface_hub-2.2.0-py3-none-any.whl (839 kB)
   ---------------------------------------- 0.0/839.9 kB ? eta -:--:--
   ---------------------------------------- 839.9/839.9 kB 5.1 MB/s  0:00:00
Using cached hf_xet-1.7.0-cp38-abi3-win_amd64.whl (3.8 MB)
Downloading httpx2-2.16.0-py3-none-any.whl (97 kB)
Downloading httpcore2-2.16.0-py3-none-any.whl (85 kB)
Downloading orjson-3.13.0-cp313-cp313-win_amd64.whl (121 kB)
Downloading pydantic-2.14.1-py3-none-any.whl (488 kB)
Downloading pydantic_core-2.50.1-cp313-cp313-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ------------------------ --------------- 1.3/2.2 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 6.5 MB/s  0:00:00
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Downloading python_multipart-0.0.32-py3-none-any.whl (30 kB)
Downloading safehttpx-0.1.7-py3-none-any.whl (9.0 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-1.9.0-py3-none-any.whl (80 kB)
Downloading tomlkit-0.14.0-py3-none-any.whl (39 kB)
Using cached typer-0.27.3-py3-none-any.whl (123 kB)
Using cached annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading annotated_types-0.8.0-py3-none-any.whl (13 kB)
Downloading brotli-1.2.1-cp313-cp313-win_amd64.whl (371 kB)
Downloading filelock-4.2.4-py3-none-any.whl (162 kB)
Using cached fsspec-2026.9.0-py3-none-any.whl (221 kB)
Downloading opentelemetry_api-1.45.1-py3-none-any.whl (60 kB)
Downloading pytz-2026.5-py2.py3-none-any.whl (506 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Downloading truststore-0.10.5-py3-none-any.whl (19 kB)
Downloading typing_inspection-0.4.4-py3-none-any.whl (14 kB)
Downloading uvicorn-0.54.0-py3-none-any.whl (87 kB)
Installing collected packages: pytz, pydub, brotli, uvicorn, typing-inspection, truststore, tomlkit, shellingham, semantic-version, python-multipart, pydantic-core, orjson, opentelemetry-api, mdurl, hf-xet, groovy, fsspec, filelock, audioop-lts, annotated-types, annotated-doc, starlette, pydantic, markdown-it-py, httpcore2, safehttpx, rich, httpx2, fastapi, typer, huggingface-hub, gradio-client, hf-gradio, gradio

   ----------------------------------------  0/34 [pytz]
   ----------------------------------------  0/34 [pytz]
   ----------------------------------------  0/34 [pytz]
   - --------------------------------------  1/34 [pydub]
   - --------------------------------------  1/34 [pydub]
   --- ------------------------------------  3/34 [uvicorn]
   --- ------------------------------------  3/34 [uvicorn]
   --- ------------------------------------  3/34 [uvicorn]
   --- ------------------------------------  3/34 [uvicorn]
   --- ------------------------------------  3/34 [uvicorn]
   --- ------------------------------------  3/34 [uvicorn]
   --- ------------------------------------  3/34 [uvicorn]
   ----- ----------------------------------  5/34 [truststore]
   ------- --------------------------------  6/34 [tomlkit]
   ------- --------------------------------  6/34 [tomlkit]
   -------- -------------------------------  7/34 [shellingham]
   ---------- -----------------------------  9/34 [python-multipart]
   ----------- ---------------------------- 10/34 [pydantic-core]
   -------------- ------------------------- 12/34 [opentelemetry-api]
   -------------- ------------------------- 12/34 [opentelemetry-api]
   -------------- ------------------------- 12/34 [opentelemetry-api]
   -------------- ------------------------- 12/34 [opentelemetry-api]
   -------------- ------------------------- 12/34 [opentelemetry-api]
   ---------------- ----------------------- 14/34 [hf-xet]
   ------------------ --------------------- 16/34 [fsspec]
   ------------------ --------------------- 16/34 [fsspec]
   ------------------ --------------------- 16/34 [fsspec]
   ------------------ --------------------- 16/34 [fsspec]
   ------------------ --------------------- 16/34 [fsspec]
   ------------------ --------------------- 16/34 [fsspec]
   ------------------ --------------------- 16/34 [fsspec]
   ------------------ --------------------- 16/34 [fsspec]
   ------------------ --------------------- 16/34 [fsspec]
   -------------------- ------------------- 17/34 [filelock]
   -------------------- ------------------- 17/34 [filelock]
   -------------------- ------------------- 17/34 [filelock]
   -------------------- ------------------- 17/34 [filelock]
   ------------------------ --------------- 21/34 [starlette]
   ------------------------ --------------- 21/34 [starlette]
   ------------------------ --------------- 21/34 [starlette]
   ------------------------ --------------- 21/34 [starlette]
   ------------------------ --------------- 21/34 [starlette]
   ------------------------ --------------- 21/34 [starlette]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   ------------------------- -------------- 22/34 [pydantic]
   --------------------------- ------------ 23/34 [markdown-it-py]
   --------------------------- ------------ 23/34 [markdown-it-py]
   --------------------------- ------------ 23/34 [markdown-it-py]
   --------------------------- ------------ 23/34 [markdown-it-py]
   --------------------------- ------------ 23/34 [markdown-it-py]
   --------------------------- ------------ 23/34 [markdown-it-py]
   --------------------------- ------------ 23/34 [markdown-it-py]
   --------------------------- ------------ 23/34 [markdown-it-py]
   --------------------------- ------------ 23/34 [markdown-it-py]
   ---------------------------- ----------- 24/34 [httpcore2]
   ---------------------------- ----------- 24/34 [httpcore2]
   ---------------------------- ----------- 24/34 [httpcore2]
   ---------------------------- ----------- 24/34 [httpcore2]
   ---------------------------- ----------- 24/34 [httpcore2]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------ --------- 26/34 [rich]
   ------------------------------- -------- 27/34 [httpx2]
   ------------------------------- -------- 27/34 [httpx2]
   ------------------------------- -------- 27/34 [httpx2]
   ------------------------------- -------- 27/34 [httpx2]
   ------------------------------- -------- 27/34 [httpx2]
   ------------------------------- -------- 27/34 [httpx2]
   -------------------------------- ------- 28/34 [fastapi]
   -------------------------------- ------- 28/34 [fastapi]
   -------------------------------- ------- 28/34 [fastapi]
   -------------------------------- ------- 28/34 [fastapi]
   -------------------------------- ------- 28/34 [fastapi]
   -------------------------------- ------- 28/34 [fastapi]
   -------------------------------- ------- 28/34 [fastapi]
   -------------------------------- ------- 28/34 [fastapi]
   ---------------------------------- ----- 29/34 [typer]
   ---------------------------------- ----- 29/34 [typer]
   ---------------------------------- ----- 29/34 [typer]
   ---------------------------------- ----- 29/34 [typer]
   ---------------------------------- ----- 29/34 [typer]
   ---------------------------------- ----- 29/34 [typer]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]
   ----------------------------------- ---- 30/34 [huggingface-hub]

In [32]:
%pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting lxml>=3.1.0 (from python-docx)
  Downloading lxml-6.1.3-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: typing_extensions>=4.9.0 in .\AppData\Roaming\Python\Python313\site-packages (from python-docx) (4.16.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
Downloading lxml-6.1.3-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------- -------------------------- 1.3/4.0 MB 7.1 MB/s eta 0:00:01
   -------------------------- ------------- 2.6/4.0 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 6.8 MB/s  0:00:00
Installing collected packages: lxml, python-docx

   ---------------------------------------- 0/2 [lxml]
   ---------------------------------------- 0/2 [lxml]
   ---------------------------------------- 0/2 [lxml]
   ---------------------------------------- 0/2 [lxml]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   ---------------------------------------- 2/2 [python-docx]

Successfully installed lxml-6.1.3 python-docx-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [33]:
%pip install gradio pypdf python-docx scikit-learn

Requirement already satisfied: gradio in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (6.30.0)
Requirement already satisfied: pypdf in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (6.21.2)
Requirement already satisfied: python-docx in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.0)
Requirement already satisfied: scikit-learn in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.1)
Requirement already satisfied: anyio<5.0,>=3.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (4.14.1)
Requirement already satisfied: audioop-lts<=0.2.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (1.2.1)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.161.1)
Requirement already satisfied: gradio-client==2.7.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (2.7.2)
Requirement already satisfied: groovy~=0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<3.0,>=1.16.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (2.2.0)
Requirement already satisfied: jinja2<4.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (2.5.0)
Requirement already satisfied: orjson~=3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (3.13.0)
Requirement already satisfied: packaging in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (26.2)
Requirement already satisfied: pandas<4.0,>=1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (3.1.0)
Requirement already satisfied: pillow<13.0,>=8.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (12.3.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (2.14.1)
Requirement already satisfied: pydub<1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.0.32)
Requirement already satisfied: pytz>=2017.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (2026.5)
Requirement already satisfied: pyyaml<7.0,>=5.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (6.0.3)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=1.0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (1.9.0)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.14.0)
Requirement already satisfied: typer<1.0,>=0.12 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.27.3)
Requirement already satisfied: typing-extensions~=4.0 in .\AppData\Roaming\Python\Python313\site-packages (from gradio) (4.16.0)
Requirement already satisfied: uvicorn>=0.14.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio) (0.54.0)
Requirement already satisfied: fsspec in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from gradio-client==2.7.2->gradio) (2026.9.0)
Requirement already satisfied: idna>=2.8 in .\AppData\Roaming\Python\Python313\site-packages (from anyio<5.0,>=3.0->gradio) (3.18)
Requirement already satisfied: typing-inspection>=0.4.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.5)
Requirement already satisfied: opentelemetry-api>=1.44.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from fastapi<1.0,>=0.115.2->gradio) (1.45.1)
Requirement already satisfied: certifi in .\AppData\Roaming\Python\Python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (2026.6.17)
Requirement already satisfied: httpcore==1.* in .\AppData\Roaming\Python\Python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in .\AppData\Roaming\Python\Python313\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (4.2.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (2.16.0)
Requirement already satisfied: tqdm>=4.42.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub<3.0,>=1.16.0->gradio) (4.70.1)
Requirement already satisfied: httpcore2==2.16.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.16.0->gradio) (2.16.0)
Requirement already satisfied: truststore>=0.10 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.16.0->gradio) (0.10.5)
Requirement already satisfied: python-dateutil>=2.9.0 in .\AppData\Roaming\Python\Python313\site-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Roaming\Python\Python313\site-packages (from pandas<4.0,>=1.0->gradio) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pydantic<=3.0,>=2.0->gradio) (2.50.1)
Requirement already satisfied: shellingham>=1.3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer<1.0,>=0.12->gradio) (15.0.0)
Requirement already satisfied: colorama in .\AppData\Roaming\Python\Python313\site-packages (from typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: lxml>=3.1.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-docx) (6.1.3)
Requirement already satisfied: scipy>=1.10.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.27.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Requirement already satisfied: six>=1.5 in .\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.9.0->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\AppData\Roaming\Python\Python313\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in .\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [53]:
# ============================================================
# TASK 4: DOCUMENT QUESTION-ANSWERING ASSISTANT
# PDF / DOCX / TXT | TF-IDF | Supporting Evidence | Gradio
# ============================================================

import os
import re
import gradio as gr
import numpy as np

from docx import Document
from pypdf import PdfReader
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

FALLBACK = "Information not found in provided document"
document_index = None


# 1. EXTRACT DOCUMENT CONTENT
def extract_document(file_path):
    ext = os.path.splitext(file_path)[1].lower()
    blocks = []

    if ext == ".txt":
        with open(file_path, "r", encoding="utf-8", errors="ignore") as f:
            blocks = [
                line.strip() for line in f.readlines()
                if line.strip()
            ]

    elif ext == ".pdf":
        reader = PdfReader(file_path)

        for page_no, page in enumerate(reader.pages, start=1):
            text = page.extract_text() or ""
            if text.strip():
                blocks.append(f"Page {page_no}: {text.strip()}")

    elif ext == ".docx":
        doc = Document(file_path)

        for paragraph in doc.paragraphs:
            text = re.sub(r"\s+", " ", paragraph.text).strip()
            if text:
                blocks.append(text)

        for table in doc.tables:
            for row in table.rows:
                cells = [
                    re.sub(r"\s+", " ", cell.text).strip()
                    for cell in row.cells
                ]

                row_text = " | ".join(cells)
                if row_text.strip():
                    blocks.append(row_text)

    else:
        raise ValueError("Upload a PDF, DOCX, or TXT file.")

    return blocks


# 2. BUILD PASSAGES WITHOUT LOSING DOCUMENT CONTENT
def create_passages(blocks, max_words=130, overlap=25):
    passages = []

    # Retain paragraphs as the source of truth.
    # Join short paragraphs together, but keep table rows intact.
    current = []
    current_words = 0

    def save_current():
        nonlocal current, current_words

        if current:
            text = " ".join(current).strip()
            if text:
                passages.append({
                    "heading": "Document",
                    "text": text,
                    "display": text
                })

        current = []
        current_words = 0

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        # Keep each table row as an independent passage.
        if "|" in block:
            save_current()
            passages.append({
                "heading": "Document table",
                "text": block,
                "display": block
            })
            continue

        words = block.split()

        if current and current_words + len(words) > max_words:
            save_current()

        current.append(block)
        current_words += len(words)

        if current_words >= max_words:
            save_current()

    save_current()

    # Split any exceptionally long passage into overlapping chunks.
    final_passages = []

    for p in passages:
        words = p["text"].split()

        if len(words) <= max_words:
            final_passages.append(p)
            continue

        step = max_words - overlap

        for start in range(0, len(words), step):
            chunk = " ".join(words[start:start + max_words]).strip()

            if chunk:
                final_passages.append({
                    "heading": p["heading"],
                    "text": chunk,
                    "display": chunk
                })

    # Remove exact duplicates.
    unique = []
    seen = set()

    for p in final_passages:
        key = p["text"].lower()

        if key not in seen:
            seen.add(key)
            unique.append(p)

    return unique


# 3. BUILD SEARCH INDEX
def build_index(file_path):
    blocks = extract_document(file_path)

    if not blocks:
        raise ValueError("No readable text was found in the document.")

    passages = create_passages(blocks)

    if not passages:
        raise ValueError("No searchable passages were created.")

    corpus = [p["display"] for p in passages]

    vectorizer = TfidfVectorizer(
        lowercase=True,
        strip_accents="unicode",
        ngram_range=(1, 2),
        sublinear_tf=True,
        stop_words="english"
    )

    matrix = vectorizer.fit_transform(corpus)

    return {
        "filename": os.path.basename(file_path),
        "blocks": blocks,
        "passages": passages,
        "vectorizer": vectorizer,
        "matrix": matrix
    }


# 4. LOOK UP HYPERPARAMETERS FROM THE DOCUMENT TABLE
def lookup_parameter(question, index):
    q = question.lower()

    parameters = [
        "n_estimators",
        "max_depth",
        "min_samples_split"
    ]

    requested = next(
        (p for p in parameters if p in q),
        None
    )

    if requested is None:
        return None

    for block in index["blocks"]:
        if "|" not in block:
            continue

        cells = [c.strip() for c in block.split("|")]

        if len(cells) >= 3 and cells[0].lower() == requested:
            return (
                f"The best value of {requested} is {cells[-1]}.",
                f"Source document: {index['filename']}\n"
                f"Supporting passage:\n{block}"
            )

    return None


# 5. RETRIEVE RELEVANT PASSAGES
def retrieve_passages(question, index, top_k=5):
    query_vector = index["vectorizer"].transform([question])

    scores = cosine_similarity(
        query_vector,
        index["matrix"]
    ).ravel()

    ranked = np.argsort(scores)[::-1]
    results = []

    for i in ranked[:top_k]:
        score = float(scores[i])

        results.append({
            "score": score,
            "heading": index["passages"][int(i)]["heading"],
            "text": index["passages"][int(i)]["text"]
        })

    return results


# 6. ANSWER QUESTIONS
def answer_question(question, index):
    q = question.lower().strip()

    # First handle parameter table questions.
    special = lookup_parameter(question, index)

    if special is not None:
        return special

    # Retrieve relevant passages.
    results = retrieve_passages(question, index, top_k=5)

    if not results:
        return (
            FALLBACK,
            f"Source document: {index['filename']}\n"
            "Supporting passage: None found."
        )

    # Feature questions: search passages for relevant project terminology.
    if any(term in q for term in [
        "feature", "features", "capability", "capabilities",
        "main function", "main functions"
    ]):
        feature_terms = [
            "phishing", "legitimate", "suspicious", "url",
            "classification", "risk", "probability",
            "dashboard", "security", "recommendation",
            "detection", "prediction", "user"
        ]

        matching = []

        for p in index["passages"]:
            text = p["text"].lower()
            hits = sum(term in text for term in feature_terms)

            if hits >= 2:
                matching.append((hits, p))

        if matching:
            matching.sort(key=lambda item: item[0], reverse=True)
            selected = [p for _, p in matching[:3]]

            answer = "\n\n".join(
                f"[Passage {i}]\n{p['text']}"
                for i, p in enumerate(selected, start=1)
            )

            sources = "\n\n".join(
                f"Source document: {index['filename']}\n"
                f"Supporting passage:\n{p['text']}"
                for p in selected
            )

            return answer, sources

    # General retrieval: do not reject all answers just because one token differs.
    best_score = results[0]["score"]

    if best_score < 0.12:
        return (
            FALLBACK,
            f"Source document: {index['filename']}\n"
            "Supporting passage: No sufficiently relevant passage found."
        )

    selected = [
        p for p in results
        if p["score"] >= max(0.03, best_score * 0.50)
    ][:3]

    answer = "\n\n".join(
        f"[Passage {i}]\n{p['text']}"
        for i, p in enumerate(selected, start=1)
    )

    sources = "\n\n".join(
        f"Source document: {index['filename']}\n"
        f"Similarity: {p['score']:.2%}\n"
        f"Supporting passage:\n{p['text']}"
        for p in selected
    )

    return answer, sources


# 7. LOAD DOCUMENT
def load_document(file_path):
    global document_index

    if file_path is None:
        document_index = None
        return "Please upload a document first."

    try:
        document_index = build_index(file_path)

        return (
            f"Document loaded: {document_index['filename']}\n"
            f"Passages created: {len(document_index['passages'])}\n"
            "You can now ask questions."
        )

    except Exception as error:
        document_index = None
        return f"Error processing document: {error}"


# 8. CHAT FUNCTION
def chat(message, history):
    global document_index

    history = history or []

    if not document_index:
        history += [
            {"role": "user", "content": message},
            {
                "role": "assistant",
                "content": "Please upload and load a document first."
            }
        ]
        return history, ""

    if not message or not message.strip():
        return history, ""

    answer, sources = answer_question(message, document_index)

    response = (
        f"{answer}\n\n"
        f"---\nEvidence and retrieval details:\n{sources}"
    )

    history += [
        {"role": "user", "content": message},
        {"role": "assistant", "content": response}
    ]

    return history, ""


# 9. CREATE CHAT INTERFACE
with gr.Blocks(title="Document Question-Answering Assistant") as demo:
    gr.Markdown("# Document Question-Answering Assistant")
    gr.Markdown(
        "Upload a PDF, DOCX, or TXT document. "
        "Ask questions and inspect the supporting text passages."
    )

    file_input = gr.File(
        label="Upload Document",
        file_types=[".pdf", ".docx", ".txt"],
        type="filepath"
    )

    load_button = gr.Button("Load Document", variant="primary")
    status = gr.Textbox(label="Document Status", lines=3)

    chatbot = gr.Chatbot(label="Conversation", height=420)

    question_box = gr.Textbox(
        label="Ask a Question",
        placeholder="What is PhishGuard AI?"
    )

    with gr.Row():
        ask_button = gr.Button("Ask", variant="primary")
        clear_button = gr.Button("Clear Conversation")

    load_button.click(
        fn=load_document,
        inputs=[file_input],
        outputs=[status]
    )

    ask_button.click(
        fn=chat,
        inputs=[question_box, chatbot],
        outputs=[chatbot, question_box]
    )

    question_box.submit(
        fn=chat,
        inputs=[question_box, chatbot],
        outputs=[chatbot, question_box]
    )

    clear_button.click(
        fn=lambda: [],
        inputs=[],
        outputs=[chatbot]
    )


# 10. LAUNCH APPLICATION
demo.launch()

* Running on local URL:  http://127.0.0.1:7873
* To create a public link, set `share=True` in `launch()`.